name: "PR Analytics"

permissions:
  issues: write
  
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: "Run script for analytics"
        run: sleep 15
      - name: cleanup
        if: cancelled()
        run: echo "Таймаут! Чистим ресурсы..."
